<form id="form-validate-price" method="post" action="" novalidate="novalidate">
    <label for="notification-container-1215">Sign up for out of stock notification</label>
    <div class="notification-container" id="notification-container-1215">
        <div class="input-fields fieldset">
            <input type="email" data-validate="{required:true, 'validate-email':true}" name="guest_email_price" id="amxnotif-guest-email_price-1215" class="input-text amxnotif-guest-email" size="30">
            <input type="hidden" name="product_id" value="1215">
        </div>
        <div class="actions-toolbar amxnotif_guest_action">
            <div class="primary">
                <button type="submit" class="action submit primary">
                    <span>Subscribe</span>
                </button>
            </div>
        </div>
    </div>
</form>