<?php
$categories = $block->getCategoryCollection();
//$block->toOptionArrayTest();
?>
<form class="form sellwithus"
      action="<?php echo $block->getFormAction() ?>"
      id="sellwithus"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Sell with us')) ?></span></legend><br />
        
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field lastname required">
            <label class="label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field companyname required">
            <label class="label" for="companyname"><span><?= $block->escapeHtml(__('Company Name')) ?></span></label>
            <div class="control">
                <input name="companyname" id="companyname" title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field companytype required">
            <label for="companytype"
                   class="label"><span><?= $block->escapeHtml(__('Company type')) ?></span></label>
            <select name="companytype" id="companytype" class="admin__control-select required-entry">
                <option value="">-Company type-</option>
                <?php foreach($block->toOptionArray() as $key=>$value){ ?>
                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                <?php }?>
            </select>
        </div>
        <div class="field address required">
            <label class="label" for="address"><span><?= $block->escapeHtml(__('Address')) ?></span></label>
            <div class="control">
                <textarea name="address" id="address" class="" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field mobno required">
            <label class="label" for="mobno"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="mobno" id="mobno" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field pincode required">
            <label class="label" for="pincode"><span><?= $block->escapeHtml(__('Pin Code')) ?></span></label>
            <div class="control">
                <input name="pincode" id="pincode" title="<?= $block->escapeHtmlAttr(__('Pin Code')) ?>" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input name="city" id="city" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text" type="text" data-validate="{required:true}" />
            </div>
        </div>
        <div class="field state required">
            <label for="state"
                   class="label"><span><?= $block->escapeHtml(__('State')) ?></span></label>
            <select name="state" id="state" class="admin__control-select required-entry">
                <option value="">-State-</option>
                <?php foreach($block->toOptionArray() as $key=>$value){ ?>
                    <option value="<?php echo $key ?>"><?php echo $value ?></option>
                <?php }?>
            </select>
        </div>
        <div class="field category required">
            <label for="category"
                   class="label"><span><?= $block->escapeHtml(__('Category')) ?></span></label>
            <select name="category" id="category" class="admin__control-select required-entry">
                <option value="">-Category-</option>
                <?php foreach ($categories as $category) { ?>
                    <option value="<?php echo $category->getId() ?>"><?php echo $category->getName(); ?></option>
                <?php }?>
            </select>
        </div>
    <input name="status" type="hidden" value="1">
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
